import { Match } from '@/types';

export const mockMatches: Match[] = [
  {
    id: 'match-1',
    sport: 'football',
    homeTeam: 'Real Madrid',
    awayTeam: 'Barcelona',
    date: '2024-02-15',
    league: 'La Liga',
    price: 29.99,
    statsYears: 5,
  },
  {
    id: 'match-2',
    sport: 'football',
    homeTeam: 'Manchester United',
    awayTeam: 'Liverpool',
    date: '2024-02-17',
    league: 'Premier League',
    price: 29.99,
    statsYears: 5,
  },
  {
    id: 'match-3',
    sport: 'basketball',
    homeTeam: 'Los Angeles Lakers',
    awayTeam: 'Boston Celtics',
    date: '2024-02-18',
    league: 'NBA',
    price: 24.99,
    statsYears: 5,
  },
  {
    id: 'match-4',
    sport: 'tennis',
    homeTeam: 'Novak Djokovic',
    awayTeam: 'Carlos Alcaraz',
    date: '2024-02-19',
    league: 'ATP Tour',
    price: 19.99,
    statsYears: 5,
  },
  {
    id: 'match-5',
    sport: 'volleyball',
    homeTeam: 'Zenit Kazan',
    awayTeam: 'Lube Civitanova',
    date: '2024-02-20',
    league: 'Champions League',
    price: 14.99,
    statsYears: 5,
  },
  {
    id: 'match-6',
    sport: 'football',
    homeTeam: 'Bayern Munich',
    awayTeam: 'Borussia Dortmund',
    date: '2024-02-21',
    league: 'Bundesliga',
    price: 29.99,
    statsYears: 5,
  },
  {
    id: 'match-7',
    sport: 'basketball',
    homeTeam: 'Golden State Warriors',
    awayTeam: 'Phoenix Suns',
    date: '2024-02-22',
    league: 'NBA',
    price: 24.99,
    statsYears: 5,
  },
  {
    id: 'match-8',
    sport: 'tennis',
    homeTeam: 'Rafael Nadal',
    awayTeam: 'Stefanos Tsitsipas',
    date: '2024-02-23',
    league: 'ATP Tour',
    price: 19.99,
    statsYears: 5,
  },
];